# Generated by Django 6.0.5 on 2026-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='contact_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
